baseURL = 'https://text-matrix.3hao8.com/'
#locale = 'en-us'
locale = 'zh'
languageCode = "zh-cn"
title = 'text matrix'
theme = "LoveIt"


enableGitInfo = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 2
